# Use the ALSA card name so USB/card enumeration changes do not break startup.
ADEVICE plughw:CODEC,0
ACHANNELS 1

CHANNEL 0
MYCALL W2QS-7

MODEM 1200

PTT RIG 2 127.0.0.1:4532

TXDELAY 100
TXTAIL 30
PERSIST 63
SLOTTIME 10

AGWPORT 8000
KISSPORT 8001

PBEACON delay=1 every=2 overlay=S symbol=">" lat=43^04.00N long=075^30.00W comment="W2QS-7 IC-7100 Direwolfing the night away"
